### ISSUE TITLE
Light and dark images in Hugo?

### ISSUE THREAD

**Issue by sonotley** [tomfran/blog#1]
Hi there, sorry for opening an issue on your blog - bit of a weird way to get in contact! I was looking at your post about how you got  light and dark mode images working in Hugo and trying to copy the approach into my own Hugo site. I noticed that it seemed to have stopped working, even in your own blog as I was seeing 404s for the images. Then the whole blog vanished! Anyway, just wanted to get in touch to see if you had a solution, or any pointers about what changed that broke your original solution.

**Comment by tomfran** [comment]
I removed the post from the blog accidentally, re-uploaded it, hope it can be useful 👍
